// Generated by Pier. Do not edit by hand.

import { app, appSlot, parseAppEnv, variable, type PierUrl } from "@pier/core";

export type PierEnvironment = "dev" | "preview" | "staging" | "prod";

const config = app({
  apps: {
    "web": appSlot.tanstackStart("apps/web/src/start.ts", {"bindings":[],"domain":"pier-demo.buildwithharbor.com","vars":["PUBLIC_API_URL","PUBLIC_APP_NAME","PUBLIC_WEB_URL"]}),
  },
  bindings: {},
  name: "pier-demo",
  vars: {
    "PUBLIC_API_URL": variable.url().default("https://api.pier-demo.buildwithharbor.com").public(),
    "PUBLIC_APP_NAME": variable.string().default("Pier Demo"),
    "PUBLIC_WEB_URL": variable.url().default("https://pier-demo.buildwithharbor.com").public()
  },
});

const publicAliases: Record<string, readonly string[]> = {"PUBLIC_API_URL":["API_URL","VITE_API_URL","VITE_PUBLIC_API_URL"],"PUBLIC_WEB_URL":["VITE_PUBLIC_WEB_URL","VITE_WEB_URL","WEB_URL"]};
const clientEnvKeys = ["PUBLIC_API_URL","VITE_API_URL","VITE_PUBLIC_API_URL","PUBLIC_WEB_URL","VITE_PUBLIC_WEB_URL","VITE_WEB_URL"] as const;

export const projectTopology = {"apps":[{"name":"admin","kind":"tanstack-start-app","domain":"admin.pier-demo.buildwithharbor.com"},{"name":"api","kind":"worker-api","domain":"api.pier-demo.buildwithharbor.com"},{"name":"internal","kind":"worker-internal","internal":true},{"name":"web","kind":"tanstack-start-app","domain":"pier-demo.buildwithharbor.com"}],"currentApp":"web","project":"pier-demo"} as const;

export interface ServerEnv {
  readonly PUBLIC_API_URL: PierUrl;
  readonly PUBLIC_APP_NAME: string;
  readonly PUBLIC_WEB_URL: PierUrl;
}

export interface ClientEnv {
  readonly PUBLIC_API_URL: PierUrl;
  readonly VITE_API_URL: PierUrl;
  readonly VITE_PUBLIC_API_URL: PierUrl;
  readonly PUBLIC_WEB_URL: PierUrl;
  readonly VITE_PUBLIC_WEB_URL: PierUrl;
  readonly VITE_WEB_URL: PierUrl;
}

export type Env = ServerEnv;

export const parseServerEnv = (rawEnv: object): ServerEnv =>
  parseAppEnv<Record<string, unknown>>(
    config,
    "web",
    {
    ...(rawEnv as Record<string, unknown>),
    "PUBLIC_API_URL": (rawEnv as Record<string, unknown>)["PUBLIC_API_URL"] ?? (rawEnv as Record<string, unknown>)["API_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_API_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_PUBLIC_API_URL"],
    "PUBLIC_WEB_URL": (rawEnv as Record<string, unknown>)["PUBLIC_WEB_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_PUBLIC_WEB_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_WEB_URL"] ?? (rawEnv as Record<string, unknown>)["WEB_URL"]
  },
    { requireBindings: false },
  ) as unknown as ServerEnv;

export const parseClientEnv = (rawEnv: object): ClientEnv =>
  selectClientEnv(withPublicAliases(parseServerEnv(rawEnv) as unknown as Record<string, unknown>)) as unknown as ClientEnv;

export const parseEnv = parseServerEnv;

export const serverEnv = new Proxy({} as ServerEnv, {
  get: (_target, property) => {
    assertServerEnvAccess(property);
    return parseServerEnv(readRuntimeEnv())[property as keyof ServerEnv];
  },
  ownKeys: () => isBrowserRuntime() ? [] : Reflect.ownKeys(parseServerEnv(readRuntimeEnv())),
  getOwnPropertyDescriptor: (_target, property) => {
    if (isBrowserRuntime()) return undefined;
    return descriptor(parseServerEnv(readRuntimeEnv()), property);
  },
});

export const clientEnv = new Proxy({} as ClientEnv, {
  get: (_target, property) => parseClientEnv(readRuntimeEnv())[property as keyof ClientEnv],
  ownKeys: () => Reflect.ownKeys(parseClientEnv(readRuntimeEnv())),
  getOwnPropertyDescriptor: (_target, property) => descriptor(parseClientEnv(readRuntimeEnv()), property),
});

export const env = serverEnv;

function assertServerEnvAccess(property: string | symbol) {
  if (!isBrowserRuntime()) return;
  throw new Error("Pier serverEnv." + String(property) + " cannot be read in browser code. Use clientEnv with a PUBLIC_ or VITE_ key instead.");
}

function isBrowserRuntime() {
  return typeof window !== "undefined";
}

function readRuntimeEnv() {
  const runtimeEnv: Record<string, unknown> = {};
  if (typeof process !== "undefined") {
    Object.assign(runtimeEnv, process.env);
  }
  Object.assign(runtimeEnv, (import.meta as ImportMeta & { readonly env?: Record<string, unknown> }).env ?? {});
  return {
    ...runtimeEnv,
  };
}

function withPublicAliases(parsed: Record<string, unknown>): Record<string, unknown> {
  const output = { ...parsed };
  for (const [name, aliases] of Object.entries(publicAliases)) {
    const value = output[name];
    if (value === undefined) continue;
    for (const alias of aliases) {
      output[alias] = value;
    }
  }
  return output;
}

function selectClientEnv(parsed: Record<string, unknown>): Record<string, unknown> {
  const output: Record<string, unknown> = {};
  for (const key of clientEnvKeys) {
    const value = parsed[key];
    if (value !== undefined) output[key] = value;
  }
  return output;
}

function descriptor(parsed: object, property: string | symbol) {
  if (!Reflect.ownKeys(parsed).includes(property)) return undefined;
  return {
    configurable: true,
    enumerable: true,
    value: (parsed as Record<string | symbol, unknown>)[property],
  };
}
