[install.scopes]
"@waypoint" = { url = "https://api.buildwithharbor.com/npm/", token = "$WAYPOINT_REGISTRY_TOKEN" }
"@repo" = { url = "https://api.buildwithharbor.com/npm/", token = "$WAYPOINT_REGISTRY_TOKEN" }
