// Generated by Pier. Do not edit by hand.

import { contextDrain, createApi as createPierApi, type ApiOperationContext } from "@pier/backend";
import { consoleDrain, type LogDrain, type LogEvent } from "@pier/log";
import { parseEnv, projectTopology, type Env } from "./env";

const defaultRuntimeLogSampleRate = 0.1;

export type PierApiContext<TExtension extends object = Record<string, never>> = ApiOperationContext<Env, TExtension>;

export const createApi = () => createPierApi<Env>({
  worker: {
    env: parseEnv,
    projectTopology,
    log: {
      drains: [consoleDrain, createPierRuntimeLogDrain()],
    },
  },
});

function createPierRuntimeLogDrain() {
  return contextDrain<Env, Record<string, never>>((ctx): LogDrain => {
    const env = ctx.env as unknown as Record<string, unknown>;
    const ingestUrl = stringEnv(env, "PIER_RUNTIME_LOG_INGEST_URL") ?? runtimeLogIngestUrl(stringEnv(env, "PIER_API_URL"));
    const ingestKey = stringEnv(env, "PIER_RUNTIME_LOG_INGEST_KEY") ?? stringEnv(env, "PIER_API_KEY");
    const sampleRate = runtimeLogSampleRate(env);
    if (!ingestUrl || !ingestKey) {
      return () => undefined;
    }

    return (event) => {
      if (!shouldIngestRuntimeLogEvent(event, sampleRate)) {
        return;
      }
      ctx.waitUntil(postPierRuntimeLog({ event, ingestKey, ingestUrl }));
    };
  });
}

function shouldIngestRuntimeLogEvent(event: LogEvent, sampleRate: number) {
  if (event.level === "error" || event.level === "warn") {
    return true;
  }
  return sampleRate >= 1 || (sampleRate > 0 && Math.random() < sampleRate);
}

async function postPierRuntimeLog(input: {
  readonly event: LogEvent;
  readonly ingestKey: string;
  readonly ingestUrl: string;
}) {
  const payload = pierRuntimeLogPayload(input.event);
  if (!payload.message) {
    return;
  }
  try {
    const response = await fetch(input.ingestUrl, {
      body: JSON.stringify(payload),
      headers: {
        "content-type": "application/json",
        "x-api-key": input.ingestKey,
      },
      method: "POST",
    });
    if (!response.ok) {
      console.warn("Pier runtime log ingest failed", response.status);
    }
  } catch (error) {
    console.warn("Pier runtime log ingest failed", error instanceof Error ? error.message : String(error));
  }
}

function pierRuntimeLogPayload(event: LogEvent) {
  const metadata = safeMetadata(event.metadata);
  return {
    ...(event.app ? { app: event.app } : { app: projectTopology.currentApp }),
    ...(event.cfRay ? { cfRay: event.cfRay } : {}),
    ...(event.deploymentId ? { deploymentId: event.deploymentId } : {}),
    ...(event.environment ? { environment: event.environment } : {}),
    format: "json" as const,
    level: event.level,
    message: event.message ?? event.name,
    ...(metadata ? { metadata: { ...metadata, eventName: event.name } } : { metadata: { eventName: event.name } }),
    projectSlug: projectTopology.project,
    ...(event.requestId ? { requestId: event.requestId } : {}),
    source: "pier-log",
    timestamp: event.timestamp,
    ...(event.traceId ? { traceId: event.traceId } : {}),
    ...(event.versionId ? { versionId: event.versionId } : {}),
    ...(event.worker ? { worker: event.worker } : { worker: projectTopology.currentApp }),
  };
}

function runtimeLogIngestUrl(apiUrl: string | undefined) {
  if (!apiUrl) {
    return undefined;
  }
  return new URL("/observability/runtime-logs", apiUrl).href;
}

function runtimeLogSampleRate(env: Record<string, unknown>) {
  const raw = stringEnv(env, "PIER_RUNTIME_LOG_SAMPLE_RATE");
  if (!raw) {
    return defaultRuntimeLogSampleRate;
  }
  const value = Number(raw);
  if (!Number.isFinite(value)) {
    return defaultRuntimeLogSampleRate;
  }
  return Math.max(0, Math.min(1, value));
}

function safeMetadata(metadata: Record<string, unknown> | undefined) {
  if (!metadata) {
    return undefined;
  }
  try {
    return JSON.parse(JSON.stringify(metadata)) as Record<string, unknown>;
  } catch {
    return { serialization: "failed" };
  }
}

function stringEnv(env: Record<string, unknown>, name: string) {
  const value = env[name];
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}
