// Generated by Pier. Do not edit by hand.

import { app, appSlot, parseAppEnv, binding, variable, type PierUrl } from "@pier/core";

export type PierEnvironment = "dev" | "preview" | "staging" | "prod";

const config = app({
  apps: {
    "api": appSlot.apiWorker("apps/api/src/index.ts", {"bindings":["CACHE","DB","INTERNAL","RATE_LIMITER"],"domain":"api.pier-demo.buildwithharbor.com","vars":["ADMIN_URL","API_URL","BETTER_AUTH_SECRET","PUBLIC_ADMIN_URL","PUBLIC_API_URL","PUBLIC_APP_NAME","PUBLIC_WEB_URL","PUBLIC_ZERO_SERVER_SCHEMA","WEB_URL"]}),
  },
  bindings: {
    "CACHE": binding.kv(),
    "DB": binding.postgres("shared"),
    "INTERNAL": binding.service("internal"),
    "RATE_LIMITER": binding.rateLimit("1001", {"limit":20,"period":60})
  },
  name: "pier-demo",
  vars: {
    "ADMIN_URL": variable.url(),
    "API_URL": variable.url(),
    "BETTER_AUTH_SECRET": variable.string().random(32).sensitive(),
    "PUBLIC_ADMIN_URL": variable.url().public(),
    "PUBLIC_API_URL": variable.url().public(),
    "PUBLIC_APP_NAME": variable.string().public(),
    "PUBLIC_WEB_URL": variable.url().public(),
    "PUBLIC_ZERO_SERVER_SCHEMA": variable.string().public(),
    "WEB_URL": variable.url()
  },
});

const publicAliases: Record<string, readonly string[]> = {"PUBLIC_ADMIN_URL":["ADMIN_URL","VITE_ADMIN_URL","VITE_PUBLIC_ADMIN_URL"],"PUBLIC_API_URL":["API_URL","VITE_API_URL","VITE_PUBLIC_API_URL"],"PUBLIC_APP_NAME":["APP_NAME","VITE_APP_NAME","VITE_PUBLIC_APP_NAME"],"PUBLIC_WEB_URL":["VITE_PUBLIC_WEB_URL","VITE_WEB_URL","WEB_URL"],"PUBLIC_ZERO_SERVER_SCHEMA":["VITE_PUBLIC_ZERO_SERVER_SCHEMA","VITE_ZERO_SERVER_SCHEMA","ZERO_SERVER_SCHEMA"]};
const clientEnvKeys = ["PUBLIC_ADMIN_URL","VITE_ADMIN_URL","VITE_PUBLIC_ADMIN_URL","PUBLIC_API_URL","VITE_API_URL","VITE_PUBLIC_API_URL","PUBLIC_APP_NAME","VITE_APP_NAME","VITE_PUBLIC_APP_NAME","PUBLIC_WEB_URL","VITE_PUBLIC_WEB_URL","VITE_WEB_URL","PUBLIC_ZERO_SERVER_SCHEMA","VITE_PUBLIC_ZERO_SERVER_SCHEMA","VITE_ZERO_SERVER_SCHEMA"] as const;

export const projectTopology = {"apps":[{"name":"admin","kind":"tanstack-start-app","domain":"admin.pier-demo.buildwithharbor.com"},{"name":"api","kind":"worker-api","domain":"api.pier-demo.buildwithharbor.com"},{"name":"internal","kind":"worker-internal","internal":true},{"name":"web","kind":"tanstack-start-app","domain":"pier-demo.buildwithharbor.com"}],"currentApp":"api","project":"pier-demo"} as const;

export interface ServerEnv {
  readonly ADMIN_URL: PierUrl;
  readonly API_URL: PierUrl;
  readonly BETTER_AUTH_SECRET: string;
  readonly PUBLIC_ADMIN_URL: PierUrl;
  readonly PUBLIC_API_URL: PierUrl;
  readonly PUBLIC_APP_NAME: string;
  readonly PUBLIC_WEB_URL: PierUrl;
  readonly PUBLIC_ZERO_SERVER_SCHEMA: string;
  readonly WEB_URL: PierUrl;
  readonly CACHE: KVNamespace;
  readonly DB: { readonly connectionString: string };
  readonly INTERNAL: Fetcher;
  readonly RATE_LIMITER: RateLimit;
}

export interface ClientEnv {
  readonly PUBLIC_ADMIN_URL: PierUrl;
  readonly VITE_ADMIN_URL: PierUrl;
  readonly VITE_PUBLIC_ADMIN_URL: PierUrl;
  readonly PUBLIC_API_URL: PierUrl;
  readonly VITE_API_URL: PierUrl;
  readonly VITE_PUBLIC_API_URL: PierUrl;
  readonly PUBLIC_APP_NAME: string;
  readonly VITE_APP_NAME: string;
  readonly VITE_PUBLIC_APP_NAME: string;
  readonly PUBLIC_WEB_URL: PierUrl;
  readonly VITE_PUBLIC_WEB_URL: PierUrl;
  readonly VITE_WEB_URL: PierUrl;
  readonly PUBLIC_ZERO_SERVER_SCHEMA: string;
  readonly VITE_PUBLIC_ZERO_SERVER_SCHEMA: string;
  readonly VITE_ZERO_SERVER_SCHEMA: string;
}

export type Env = ServerEnv;

export const parseServerEnv = (rawEnv: object): ServerEnv =>
  parseAppEnv<Record<string, unknown>>(
    config,
    "api",
    {
    ...(rawEnv as Record<string, unknown>),
    "PUBLIC_ADMIN_URL": (rawEnv as Record<string, unknown>)["PUBLIC_ADMIN_URL"] ?? (rawEnv as Record<string, unknown>)["ADMIN_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_ADMIN_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_PUBLIC_ADMIN_URL"],
    "PUBLIC_API_URL": (rawEnv as Record<string, unknown>)["PUBLIC_API_URL"] ?? (rawEnv as Record<string, unknown>)["API_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_API_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_PUBLIC_API_URL"],
    "PUBLIC_APP_NAME": (rawEnv as Record<string, unknown>)["PUBLIC_APP_NAME"] ?? (rawEnv as Record<string, unknown>)["APP_NAME"] ?? (rawEnv as Record<string, unknown>)["VITE_APP_NAME"] ?? (rawEnv as Record<string, unknown>)["VITE_PUBLIC_APP_NAME"],
    "PUBLIC_WEB_URL": (rawEnv as Record<string, unknown>)["PUBLIC_WEB_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_PUBLIC_WEB_URL"] ?? (rawEnv as Record<string, unknown>)["VITE_WEB_URL"] ?? (rawEnv as Record<string, unknown>)["WEB_URL"],
    "PUBLIC_ZERO_SERVER_SCHEMA": (rawEnv as Record<string, unknown>)["PUBLIC_ZERO_SERVER_SCHEMA"] ?? (rawEnv as Record<string, unknown>)["VITE_PUBLIC_ZERO_SERVER_SCHEMA"] ?? (rawEnv as Record<string, unknown>)["VITE_ZERO_SERVER_SCHEMA"] ?? (rawEnv as Record<string, unknown>)["ZERO_SERVER_SCHEMA"],
    "DB": (rawEnv as Record<string, unknown>)["DB"] ?? ((rawEnv as Record<string, unknown>).DATABASE_URL ? { connectionString: (rawEnv as Record<string, unknown>).DATABASE_URL } : undefined)
  },
    { requireBindings: false },
  ) as unknown as ServerEnv;

export const parseClientEnv = (rawEnv: object): ClientEnv =>
  selectClientEnv(withPublicAliases(parseServerEnv(rawEnv) as unknown as Record<string, unknown>)) as unknown as ClientEnv;

export const parseEnv = parseServerEnv;

export const serverEnv = new Proxy({} as ServerEnv, {
  get: (_target, property) => {
    assertServerEnvAccess(property);
    return parseServerEnv(readRuntimeEnv())[property as keyof ServerEnv];
  },
  ownKeys: () => isBrowserRuntime() ? [] : Reflect.ownKeys(parseServerEnv(readRuntimeEnv())),
  getOwnPropertyDescriptor: (_target, property) => {
    if (isBrowserRuntime()) return undefined;
    return descriptor(parseServerEnv(readRuntimeEnv()), property);
  },
});

export const clientEnv = new Proxy({} as ClientEnv, {
  get: (_target, property) => parseClientEnv(readRuntimeEnv())[property as keyof ClientEnv],
  ownKeys: () => Reflect.ownKeys(parseClientEnv(readRuntimeEnv())),
  getOwnPropertyDescriptor: (_target, property) => descriptor(parseClientEnv(readRuntimeEnv()), property),
});

export const env = serverEnv;

function assertServerEnvAccess(property: string | symbol) {
  if (!isBrowserRuntime()) return;
  throw new Error("Pier serverEnv." + String(property) + " cannot be read in browser code. Use clientEnv with a PUBLIC_ or VITE_ key instead.");
}

function isBrowserRuntime() {
  return typeof window !== "undefined";
}

function readRuntimeEnv() {
  const runtimeEnv: Record<string, unknown> = {};
  if (typeof process !== "undefined") {
    Object.assign(runtimeEnv, process.env);
  }
  Object.assign(runtimeEnv, (import.meta as ImportMeta & { readonly env?: Record<string, unknown> }).env ?? {});
  return {
    ...runtimeEnv,
  };
}

function withPublicAliases(parsed: Record<string, unknown>): Record<string, unknown> {
  const output = { ...parsed };
  for (const [name, aliases] of Object.entries(publicAliases)) {
    const value = output[name];
    if (value === undefined) continue;
    for (const alias of aliases) {
      output[alias] = value;
    }
  }
  return output;
}

function selectClientEnv(parsed: Record<string, unknown>): Record<string, unknown> {
  const output: Record<string, unknown> = {};
  for (const key of clientEnvKeys) {
    const value = parsed[key];
    if (value !== undefined) output[key] = value;
  }
  return output;
}

function descriptor(parsed: object, property: string | symbol) {
  if (!Reflect.ownKeys(parsed).includes(property)) return undefined;
  return {
    configurable: true,
    enumerable: true,
    value: (parsed as Record<string | symbol, unknown>)[property],
  };
}
